name: Build

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint + Static Analysis
    steps:
    - uses: actions/checkout@v5

    - name: "Set up Python"
      uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"

    - name: Install UV
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Install Task
      run: sudo snap install task --classic

    - name: Install Deps
      run: task venv
      env:
        ARCH: cpu

    - name: mypy cache
      uses: actions/cache@v4
      with:
        path: .mypy_cache
        key: ${{ runner.os }}-mypy-${{ hashFiles('pyproject.toml') }}
        restore-keys: ${{ runner.os }}-mypy-

    - name: Lint
      run: task lint-ci

  test:
    runs-on: ubuntu-latest
    name: E2E and Unit Tests
    steps:
    - uses: actions/checkout@v5

    - name: Restore API Cache
      uses: actions/cache@v3
      with:
        path: resources/tools/api_cache.db
        key: ${{ runner.os }}-api-cache-${{ hashFiles('**/*.py') }}
        restore-keys: ${{ runner.os }}-api-cache-

    - name: "Set up Python"
      uses: actions/setup-python@v6
      with:
        python-version-file: ".python-version"

    - name: Install UV
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true

    - name: Install Task
      run: sudo snap install task --classic

    - name: Install Deps
      run: task venv
      env:
        ARCH: cpu

    - name: Run Tests
      run: task test
      env:
        LANGSMITH_TRACING: false
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        SPOONACULAR_API_KEY: ${{ secrets.SPOONACULAR_API_KEY }}
        RAPIDAPI_API_KEY: ${{ secrets.RAPIDAPI_API_KEY }}